### ISSUE TITLE
Scripts for converting standard ForestGEO data into format needed by inventory init

### ISSUE THREAD

**Issue by JessicaNeedham** [NGEET/fates-tutorial#10]
This depends a bit on the related FATES issue [#1062](https://github.com/NGEET/fates/issues/1062).

```[tasklist]
### Tasks
- [x] Clean up inventory initialization files needed by FATES
- [x] PR  for inventory initialization clean up
- [x] Update user guide and tech note for inventory init clean up
- [x] Write scripts for converting from ForestGEO to FATES format
- [x] PR for user guide
- [x] Script to conver ed to fates format
```
