### ISSUE TITLE
Environment Testing

### ISSUE THREAD

**Issue by glemieux** [NGEET/fates-tutorial#15]
Test the end-to-end workflow on windows and macos.  If there is time, test with different versions of the OS.

Close this out post successful beta-test.

```[tasklist]
### Tasks
- [x] macos arm64 testing
- [x] windows 11 test
- [x] macos amd64 testing
- [ ] (optional) ubuntu 22.04 testing
```

**Comment by glemieux** [comment]
Note that some users are running into issues installing docker on Windows: https://github.com/NGEET/fates-tutorial/discussions/48

**Comment by glemieux** [comment]
Testing on windows and macos is complete.
