### ISSUE TITLE
Setup docker compose to construct end-to-end container workflow

### ISSUE THREAD

**Issue by glemieux** [NGEET/fates-tutorial#16]
Ideally we would like to have the users (and developers) simply run a single command to set up both the fates container, the jupyter container, and connect the two.  Automating this with `docker compose` would help us avoid issues during setup due to users conducting operations out of order manually.
```[tasklist]
### Tasks
- [x] docker-compose.yml
- [x] run `compose up` and `down` test
- [x] How do I keep the elm-fates container running?
- [x] Address https://github.com/NGEET/tutorial-containers/issues/4#issuecomment-2241337061
- [x] How do I launch jupyter if docker compose is run in detached mode?
- [x] test sharing output across data volume
- [x] Update elm-fates container to contain cime
- [x] Restructure where the docker compose scripts will be mounted relative to the tutorial and container repos
- [ ] ~Add case scripts to the container (via COPY or WGET)~
- [ ] https://github.com/NGEET/fates-tutorial/issues/23
- [ ] https://github.com/NGEET/fates-tutorial/issues/29
- [ ] https://github.com/NGEET/tutorial-containers/issues/5
- [ ] (Optional) setup development container: https://containers.dev/overview
- [ ] https://github.com/NGEET/fates-tutorial/issues/43
```

Current process is as follows:
1. Update `env-template` file with local folders and rename to `.env`
2. `docker compose up -d`: use `compose` to start both containers in detached mode
3. `docker exec tutorial-notebook jupyter server list` to expose the jupyter url to enable launching it
4. `docker exec -it elm-fates /bin/bash` to enter interactive shell with the host land model and fates

**Comment by glemieux** [comment]
Added helper script `launch_jupyter` for windows and mac/linux machines per #43.  There are still some outstanding issues, but the workflow is operational as is.
