### ISSUE TITLE
Pre-tutorial homework communications with attendees

### ISSUE THREAD

**Issue by glemieux** [NGEET/fates-tutorial#19]
```[tasklist]
### Tasks
- [x] Send out docker installation homework
- [x] Check in on docker installation progress
- [x] Send out cleaning inventory files instructions and request for lat/lon
- [ ] ~Add instructions about giving docker permissions to where the data is kept~
- [x] Send out readthedocs fates tutorial container instructions
```
