### ISSUE TITLE
Update jupyter notebook image dockerfile with necessary packages

### ISSUE THREAD

**Issue by glemieux** [NGEET/fates-tutorial#22]
```[tasklist]
### Tasks
- [ ] https://github.com/NGEET/fates-tutorial/issues/25
- [ ] https://github.com/NGEET/fates-tutorial/issues/23
- [ ] Add `ncdf4` R package
- [ ] Add `fields` R package
```

**Comment by glemieux** [comment]
Duplicate; See #25
