### ISSUE TITLE
Add necessary conda packages to jupyter dockerfile image

### ISSUE THREAD

**Issue by glemieux** [NGEET/fates-tutorial#25]
See https://github.com/NGEET/tutorial-containers/blob/ngeet-2024/docker/baseos/gcc1120/Dockerfile for reference
```[tasklist]
### Tasks
- [x] Attempt install via `apt-get`
- [x] Test install via install with `ncdf4`
- [x] Conda install `netcdf4`
- [x] Add `fields` R package
- [x] Add `RColorBrewer` R package
- [ ] Install `r-ncdf4`using specific version corresponding to the R version in the container
```

**Comment by glemieux** [comment]
This is effectively complete.  If there is time I will pin the `r-netcdf4` version, but it would be best not to to avoid potential unforeseen compatibility issue.
