### ISSUE TITLE
Develop script to launch jupyter lab

### ISSUE THREAD

**Issue by glemieux** [NGEET/fates-tutorial#43]
```[tasklist]
### Tasks
- [ ] https://github.com/NGEET/tutorial-containers/issues/4
- [x] Add jupyterlab launch script (linux/macos)
- [x] Add jupyter lab launch script (windows powershell)
```

**Comment by glemieux** [comment]
It appears that while there are pre and post hooks for _building_ docker images, docker-compose does not offer such functionality for running processes on the host: https://github.com/docker/compose/issues/1341.  

The simplest option for providing the tutorial users with an less complex method for firing up the notebook is to provide a simple launch script.

**Comment by glemieux** [comment]
Handy command line reference: https://ss64.com/

**Comment by glemieux** [comment]
Closing with 7ad620974b34a7fec02ac9615b677851717ef41e
