### ISSUE TITLE
Build default data script

### ISSUE THREAD

**Issue by glemieux** [NGEET/fates-tutorial#5]
Try doing this from the old elm docker version: https://github.com/glemieux/docker-fates-tutorial/blob/e3sm/docker/baseos/gcc/gcc650/Dockerfile
```[tasklist]
### Tasks
- [x] Determine where lnd/clm2 data can be publicly accessed
- [x] Determine where atm/datm7 data can be publically accessed
- [x] Add script call to docker compose workflow
- [x] ~Create stub file for the fates land use series~
```

**Comment by glemieux** [comment]
This is actually managed by developing a dockerfile to go grab the data and build an image with the necessary files.
