### ISSUE TITLE
Update ELM-FATES docker image to more recent version

### ISSUE THREAD

**Issue by glemieux** [NGEET/fates-tutorial#6]
Current version is 4 years out of date at this point.  Bring this up to a more recent ELM-FATES API tag.
```[tasklist]
### Tasks
- [x] Install docker-desktop for linux on lobata
- [x] Install docker engine on lobata
- [x] Create a new e3sm-fates image with a more recent fates tag/e3sm hash
- [x] Test run [ngeetropics/elmtest image](https://hub.docker.com/r/ngeetropics/elmtest)
```
